### ISSUE TITLE
Unable to use a project from a text source.

### ISSUE THREAD

**Issue by nikpivkin** [apple/pkl-go#115]
I get an error when loading project and Pkl file as `TextSource`.

Output:
```bash
❯ go run .
panic: –– Pkl Error ––
        Cannot import dependency because project URI `repl:text/PklProject` does not have a hierarchical path.

        1 | amends "@cfn/template.pkl"
                   ^^^^^^^^^^^^^^^^^^^
        at text (repl:text)
```

```go
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/apple/pkl-go/pkl"
)

func loadProject(ctx context.Context) (*pkl.Project, error) {
	b, err := os.ReadFile("PklProject")
	if err != nil {
		return nil, err
	}

	ev, err := pkl.NewEvaluator(ctx, pkl.PreconfiguredOptions)
	if err != nil {
		return nil, err
	}

	var proj pkl.Project
	if err := ev.EvaluateOutputValue(ctx, pkl.TextSource(string(b)), &proj); err != nil {
		return nil, err
	}
	return &proj, nil
}

func main() {

	proj, err := loadProject(context.Background())
	if err != nil {
		panic(err)
	}

	evaluatorOptionsFunc := func(opts *pkl.EvaluatorOptions) {
		pkl.WithDefaultAllowedResources(opts)
		pkl.WithDefaultAllowedModules(opts)
		pkl.WithOsEnv(opts)
		pkl.WithDefaultCacheDir(opts)
		pkl.WithProject(proj)(opts)
		opts.OutputFormat = "yaml"
	}

	b, err := os.ReadFile("test.pkl")
	if err != nil {
		panic(err)
	}

	ev, err := pkl.NewEvaluator(context.Background(), evaluatorOptionsFunc)
	if err != nil {
		panic(err)
	}
	defer ev.Close()

	yaml, err := ev.EvaluateOutputText(context.Background(), pkl.TextSource(string(b)))
	if err != nil {
		panic(err)
	}

	fmt.Println(yaml)
}
```

test.pkl:
```pkl
amends "@cfn/template.pkl"
import "@cfn/cloudformation.pkl" as cfn
import "@cfn/aws/s3/bucket.pkl" as bucket

Description = "Create a bucket"

Metadata { 
    ["Foo"] = "bar"
}

Parameters {
    ["Name"] {
        Type = "String"
        Default = "baz"
    }
}

Resources {
    ["TypedBucket"] = new bucket.Bucket {
        BucketName = cfn.Ref("Name")
    }
}
```

PklProject:
```pkl
amends "pkl:Project"

dependencies {
    ["cfn"] {
        uri = "package://github.com/aws-cloudformation/cloudformation-pkl/releases/download/cloudformation@0.1.1/cloudformation@0.1.1"
    }
}
```

**Comment by nikpivkin** [comment]
If I load a file as `FileSource` and not `TextSource`:
```go
yaml, err := ev.EvaluateOutputText(context.Background(), pkl.FileSource("./test.pkl"))
	if err != nil {
		panic(err)
	}
```
It causes panic: `panic: org.pkl.core.PklBugException: An unexpected error has occurred. Would you mind filing a bug report?`

**Comment by bioball** [comment]
Not sure why you're seeing the PklBugException, but I do see some other issue with your code.

First, you should use `pkl.FileSource` instead of `pkl.TextSource`, especially if you want to use dependency notation.

Second, your `evaluatorOptionsFunc` should place `pkl.WithProject` _first_, because otherwise it blows away the rest of the settings that you are giving it. Try this:

```go
	evaluatorOptionsFunc := func(opts *pkl.EvaluatorOptions) {
		pkl.WithProject(proj)(opts)
		pkl.WithDefaultAllowedResources(opts)
		pkl.WithDefaultAllowedModules(opts)
		pkl.WithOsEnv(opts)
		pkl.WithDefaultCacheDir(opts)
		opts.OutputFormat = "yaml"
	}
```

Third, the pkl-go library provides a `NewProjectEvaluator` that takes care of the cruft of setting up the project for you. Also there's `pkl.MaybePreconfiguredOptions` that's designed to work well here. Your code can be simplified to:

```go
package main

import (
	"context"
	"fmt"

	"github.com/apple/pkl-go/pkl"
)

func main() {
	ev, err := pkl.NewProjectEvaluator(
		context.Background(),
		".",
		pkl.MaybePreconfiguredOptions,
		func(options *pkl.EvaluatorOptions) {
			options.OutputFormat = "yaml"
		},
	)
	if err != nil {
		panic(err)
	}
	yaml, err := ev.EvaluateOutputText(context.Background(), pkl.FileSource("test.pkl"))
	if err != nil {
		panic(err)
	}
	fmt.Println(yaml)
}
```

**Comment by nikpivkin** [comment]
Hi @bioball ! Thanks for the quick response.

> First, you should use `pkl.FileSource` instead of `pkl.TextSource`, especially if you want to use dependency notation.

Why? Why does it matter where I load dependencies from? I won't have access to the filesystem in the future, so I can't use `FileSource`.

> Second, your `evaluatorOptionsFunc` should place `pkl.WithProject` _first_, because otherwise it blows away the rest of the settings that you are giving it. Try this:

I forgot to update the example where I apply the project option first: https://gist.github.com/nikpivkin/2d4fcfe2f4cb09868db4accfc0a3bca1

> Third, the pkl-go library provides a `NewProjectEvaluator` that takes care of the cruft of setting up the project for you

I've seen these ways to load the project, but they don't work for me because they work with the file system.

**Comment by bioball** [comment]
Sounds good!

Embedding an FS is a good way to go. But, I _highly_ recommend that you choose another scheme instead of `file`. The `file` scheme is a well known scheme that's meant to be backed by an operating system's file system.

Many of our users use `embedfs` as a scheme instead for things like this.
