### ISSUE TITLE
Evaluate (or run output) to check for validation errors before/during/after loading data

### ISSUE THREAD

**Issue by ZackarySantana** [apple/pkl-go#17]
My current pkl configuration does some validation that happens in the output field. I don't think the validation can be done cleanly and as efficiently if it is not handled there. This can result in someone having an unhappy (or unvalidated) pkl file in which I'm trying to load upon my generated structs- but my go code would never know since the output is not ran by default.

Is there a way to evaluate or run for the output just to pass through any potential errors to my go code to handle appropriately?

**Comment by ZackarySantana** [comment]
I looked further in to the evaluator in the implementation and here is an example of evaluating the output.value to check for validation and then evaluating the module.

```
if !strings.HasSuffix(path, ".pkl") {
	return nil, errors.New("unsupported file type for configuration file (.pkl only)")
}
var source *pkl.ModuleSource
if strings.HasPrefix(path, "http://") || strings.HasPrefix(path, "https://") {
	source = pkl.UriSource(path)
} else {
	source = pkl.FileSource(path)
}

evaluator, err := pkl.NewEvaluator(ctx, pkl.PreconfiguredOptions)
if err != nil {
	return nil, err
}
defer func() {
	cerr := evaluator.Close()
	if err == nil {
		err = cerr
	}
}()

// Check validation through output.value.
_, err = evaluator.EvaluateExpressionRaw(ctx, source, "output.value")
if err != nil {
	return nil, err
}
// Evaluate the module and return the result.
var v mystruct.Data
if err := evaluator.EvaluateModule(ctx, source, &v); err != nil {
	return nil, err
}
return &v, nil
```

**Comment by holzensp** [comment]
That is one way to do it. Another is that you have some
```
hidden moduleNameHereValidated: Boolean
```
and set some
```
propertyYouKnowWillAlwaysBeConsumed = if (!moduleNameHereValidated) throw("Validation failed) else value
```
