### ISSUE TITLE
Feature Request: Add the ability to map to functions.

### ISSUE THREAD

**Issue by mattdurham** [apple/pkl-go#18]
If given something like `extern func DoSomething(some:striong): Any` it would be nice to register that handler somewhere in the go code to be called when hit.

**Comment by holzensp** [comment]
This is unlikely to get scheduled without a very strong case study / design doc / problem definition. Pkl already has a [Resource Reader SPI](https://github.com/apple/pkl/blob/0.25.2/pkl-core/src/main/java/org/pkl/core/resource/ResourceReader.java) (also for other languages, including Go), which allows you to define your own `read` schemes. _Functions_ are very deeply integrated in the interpreter and _need to be_ referentially transparent for our caching semantics to work. Giving a _general_ call-out facility would break that assumption.
