### ISSUE TITLE
Why does the following pkl panic on unmarshal?

### ISSUE THREAD

**Issue by assembly-winston** [apple/pkl-go#23]
I have a json that I wish to convert to pkl:

```
{
  "name": "something",
  "secrets": {
      "1": {
      "key": "...",
      "value": "..."
    },"2": {
      "key": "...",
      "value": "..."
    }
  }
}
```

And I unmarshal this in Go as:

```
type SomeStruct struct {
	Name    string `json:"name"`
	Env     string `json:"env"`
	Secrets map[string]struct {
		Key   string `json:"key"`
		Value string `json:"value"`
	} `json:"secrets"`
}
```

And this works!

The equivalent PKL, unless I am wrong, would be:

```
name = "something"

secrets {
    name1 {
        key = ""
        value = ""
    }
    name2 {
       key = ""
       value = ""
    }
}
```

on pkl unmarshal, however (or with evaluator, doesn't matter), the evaluation causes a fatalpanic. (and yes, I changed the struct tags to `pkl`)

```
$ go run main.go
panic: invalid code for slices: 1
```

**Comment by assembly-winston** [comment]
Simplest version of the Go code:

```
type SecretsFile struct {
	Name    string `pkl:"name"`
	Env     string `pkl:"env"`
	Secrets map[string]struct {
		Key   string `pkl:"key"`
		Value string `pkl:"value"`
	} `pkl:"secrets"`
}

func main() {
	var s SecretsFile
	f, err := os.ReadFile("sample.pkl")
	if err != nil {
		panic(err)
	}

	err = pkl.Unmarshal(f, &s)
	if err != nil {
		panic(err)
	}
	fmt.Println(s)
}
```

**Comment by bioball** [comment]
Ah, I see!

When using pkl-go, you need to use the evaluator API. This is because Pkl is a language that needs to be evaluated to produce a result.

To read more about the evaluator API, take a read through our docs here: https://pkl-lang.org/go/current/evaluation.html#without-code-generation

**Comment by assembly-winston** [comment]
I tried using the evaluator API, but it has the same panic, as I mentioned in the original comment.

**Comment by bioball** [comment]
Do you have the `pkl` CLI installed on your machine?

Do you have a code snippet that you can share?

**Comment by assembly-winston** [comment]
```
❯ pkl -v
Pkl 0.25.2 (macOS 14.2, native)

❯ go run main.go
panic: invalid code for slices: 1

goroutine 1 [running]:
main.main()
```

```
type SecretsFile struct {
	Name    string `pkl:"name"`
	Env     string `pkl:"env"`
	Secrets map[string]struct {
		Key   string `pkl:"key"`
		Value string `pkl:"value"`
	} `pkl:"secrets"`
}

func main() {
	p, err := pkl.NewEvaluator(context.Background(), pkl.PreconfiguredOptions)
	if err != nil {
		panic(err)
	}

	var s SecretsFile
	err = p.EvaluateOutputValue(context.Background(), pkl.FileSource("sample.pkl"), &s)
	if err != nil {
		panic(err)
	}
	fmt.Println(s)
}
```

**Comment by bioball** [comment]
Got it. The issue here is that your Pkl doesn't match the resulting Go shape.

Try this:

```groovy
name = "hi"

env = "hi"

secrets: Mapping<String, Secret> = new {
  ["foo"] {
    key = "bar"
    value = "baz"
  }
}

class Secret {
  key: String
  value: String
}
```

And, like I mentioned earlier in https://github.com/apple/pkl-go/issues/23#issuecomment-1977146542, the best way to hold this is to define a schema separately from your data.

Also, a simple way to ensure that the Go matches your Pkl is to use the [code generator](https://pkl-lang.org/go/current/codegen.html)
