### ISSUE TITLE
Error loading package from remote URI

### ISSUE THREAD

**Issue by ericzbeard** [apple/pkl-go#38]
Not sure if this is a bug, or if I missed a setting somewhere. I have a Pkl project that loads from a remote package, and `pkl eval` works fine. But when I do the equivalent thing from my Go code, I get this error:

```sh
error packaging template 'bucket.pkl': –– Pkl Error ––
Cannot import dependency because there is no project found.

If you meant to import a path that starts with `@`, prefix the path with `./` (e.g. `import "./@myPath").
If you meant to import a dependency, ensure that this file is within a directory that contains a PklProject module.

1 | amends "@cfn/template.pkl"
           ^^^^^^^^^^^^^^^^^^^
at bucket (file:///Users/ezbeard/Source/Cfn/try/try-guard/bucket.pkl)
```

The code that does this is [here](https://github.com/aws-cloudformation/rain/blob/main/pkl/pkl.go#L10).

Options I'm using:

```go
var EvaluatorOptionsFunc = func(opts *pkl.EvaluatorOptions) {
	pkl.WithDefaultAllowedResources(opts)
	pkl.WithOsEnv(opts)
	pkl.WithDefaultAllowedModules(opts)
	pkl.WithDefaultCacheDir(opts)
	opts.Logger = pkl.NoopLogger
	opts.OutputFormat = "yaml"
}
```

Also note that if I load local packages, the Go code works fine. It's only when I have a PklProject with a remote URI.

**Comment by bioball** [comment]
You need to construct an evaluator that understands your project, using [NewProjectEvaluator](https://pkg.go.dev/github.com/apple/pkl-go/pkl#NewProjectEvaluator).

**Comment by francknouama** [comment]
In the same context, or maybe it is a different issue. I tried to the tool in the context of my company, but I think that with the lack of support for proxy settings, I'm not able to run it properly and fetch external packages. Do we have a plan to support Proxy Settings going forward already in the roadmap?

**Comment by holzensp** [comment]
Although, yes, this is a very different issue, proxying is now supported (in 0.26.0), @francknouama.

Closing this, presuming it was addressed (please feel free to re-open if not-so, @ericzbeard)
