### ISSUE TITLE
Possible nil panic in handleReadResource

### ISSUE THREAD

**Issue by jackkleeman** [apple/pkl-go#4]
https://github.com/apple/pkl-go/blob/e613557583591edfe4f0b987d516d854572fbdcf/pkl/evaluator.go#L170-L178

Need to return if the url doesn't parse or u will be nil and we will panic

**Comment by jackkleeman** [comment]
And I think there are lots of other instances in the same file

**Comment by bioball** [comment]
Right you are; submitted #5 to fix
