### ISSUE TITLE
Use pkl-go to generate PKL files from go structs

### ISSUE THREAD

**Issue by ycz-dd** [apple/pkl-go#54]
I see #25 and I want it 👍 

## Why?
For similar reasons to #25, I have configuration as go structs and we want to test out PKL from it.  More generally, if we use go structs as an internal source of truth, I'd like to have PKL as the output for other users to consume.  

I guess a current approach could be:
1. generate JSON Schema in [go](github.com/invopop/jsonschema)
2. use [pkl binary](https://github.com/apple/pkl/issues/92#issuecomment-1936593897) to convert that to a PKL file

How do you folks recommend sharing configuration and specs with PKL that originates from a Go package?

**Comment by holzensp** [comment]
It seems a counter-pattern to me to use a system with (possibly) weaker guarantees than Pkl as a source of truth, and to only use Pkl as the wire-format. In those cases, I'd use JSON, because it's more ubiquitous. What is the added-value you're hoping to get from this approach?

**Comment by ycz-dd** [comment]
Ahh, I've been using JSON and YAML for configuration communication (on the wire).  The benefit of using PKL here would be type safety between systems (compared to implementing YAML parsers).

If I understand correctly what you're saying:
 1. PKL should be the source of truth for communicating configuration between systems
 2. Go structs that represent the boundary should be generated from PKL, kind of like protos

More I think about it, more I like that idea.  I'll go with it.

Then going from go structs to PKL would be useful for migrating existing configuration logic to PKL.  Like a migration tool, scaffolding tool for PKL.  Thoughts for that use case?

**Comment by holzensp** [comment]
What intervention on the wire are you protecting against? If it's accidental edits, I'd suggest binary protobuf. If it's malicious edits, I'd recommend encryption. Only if it's about letting it sit on disk _and be maintained there_ would I go for this.

If it's only about migration, the thing to consider is that if you instrument the Go Structs -> Pkl too smoothly, there is no reason to migrate, so the "migration" will just be a build step.

Anyway; this Issue implies Pkl would have to know how to parse Go code (and all ways to define structs; not entirely sure whether you're asking only for the schema to be generated, or whether this should include data). Alternatively, the suggestion is to use [Go's `reflect`](https://pkg.go.dev/reflect), to dump out an _instance of_ a struct to Pkl code. Either way sounds like the world upside down, to me (reasonable people can disagree).

I'd be more inclined to write an entirely separate tool that reads Go code and dumps out a Pkl schema.

**Comment by ycz-dd** [comment]
Yeah it'd be more for accidental edits.  Thank you Phillip, this makes sense.
